### ISSUE TITLE
Initial Roadmap: Example notebooks

### ISSUE THREAD

**Issue by mberz** [pyfar/gallery#12]
## Description

- Notebooks for general Tasks and Application examples could get separate sections on readthedocs

General tasks

- [x] Find best way to link between notebooks and other parts of readthedocs
- [x] Decide: Make notebooks downloadable
- [x] Setup myBinder.org / jupyter.org/hub / google code lab / github code spaces. Requirements
  - Read notebooks and resources from github
  - host multiple notebooks
  - No login required
  - Docker container
- [x] Update pyfar.org or completely move to gallery as the main homepage? (Fabian)
- [x] Add links between notebooks and to and from the documentation of other packages
- [x] In each notebook, mention at the beginning if there are other examples that should be read first (?)

Notebooks showing simple pyfar functionality as part of the pyfar docs

- [x] Working with Audio Objects (Fabian) #4 
- [x] Working with Coordinates Objects (Anne) #6 
- [x] Working with Orientation Objects (Anne) #14
- [x] Plotting Data from Audio Objects (Pascal) #23 
- [x] Reading and Writing Data to Disk
- [x] FFT and FFT conventions (Simon) #28 
- [x] Arithmetic Operations on Audio Objects (Fabian) #10 
- [x] Filtering Signal Objects (Fabian) #9 

Notebooks implementing DSP tasks/examples/applications
(potentially put in a separate repository)

- [x] Sweep based IR measurement (Fabian) #10 
- [ ] Audio artifacts
- [x] Add examples from sofar #31 
- [ ] Impulse response alignment
- [ ] Loudspeaker equalization and cross-over (Marco)
- [x] Binaural synthesis #24 
- [ ] Reverberation time (Marco)

## Notebooks for the application gallery

- [x] Overview of Filter Types (Fabian) #16 

## Final touches on Homepage
- [x] Sort notebooks
- [x] CC-BY logo in Notebooks not found (maybe must be added to static)  #46
- [x] Switch for dar/light mode went away (probably edit conf.py)
- [x] Insert blank lines to unify layout of short package descriptions
- [x] Add image for coming next
- [x] Change number of colums to 3 or less (see mobile view) #36 
- [x] Add QR Code with the final link for the DAGA Notebook #47

**Comment by mberz** [comment]
@f-brinkmann The logo is directly included from the CC homepage. It seems, that VSCode is sometimes messing that up. On binder and readthedocs, this issue does not seem to persist.
