### ISSUE TITLE
Roadmap: Move to readthedocs as main homepage

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/gallery#19]
- [x] link from pyfar.org to readthedocs
- [x] 1: General description of pyfar
- [x] 2. Add boxes for each pyfar package: pyfar, spharpy, sofar, pyrato, and for packes in progess...
- [x] 3. Notebook gallery
- [x] 4. Contributing
- [x] 5. Logo park

- Should be similar to pyfar.org but including example gallery
- General theme Documentation: https://pydata-sphinx-theme.readthedocs.io/en/stable/
- Good examples of what is possible: https://numpy.org/doc/stable/, https://www.pymc.io/welcome.html, https://matplotlib.org/, https://github.com/pymc-devs/pymc.io

**Comment by mberz** [comment]
merged in #29
